### ISSUE TITLE
Dashboard container needs to be restarted before Portal will work

### ISSUE THREAD

**Issue by davegarvey** [TykTechnologies/tyk-pro-docker-demo#17]
During the `setup.sh` script, it adds a default portal page then calls the Dashboard API `/admin/system/reload`. This creates an entry `Generating portal for: www.tyk-portal-test.com` in the Dashboard log, but visiting the portal URL (http://www.tyk-portal-test.com:3000/portal/) results in a 'Not Found' response in the browser.

Restarting the Dashboard container allows the Portal to work ok, but shouldn't the call to `/admin/system/reload` also do this?

**Comment by ilijabojanovic** [comment]
@davegarvey restart will fix problem, reload only reloads portal content but not domain names (portal routes)
