### ISSUE TITLE
Website documentation still links to quickstart repo

### ISSUE THREAD

**Issue by l3ender** [TykTechnologies/tyk-pro-docker-demo#21]
https://tyk.io/docs/get-started/with-tyk-on-premise/installation/docker/docker-quickstart/

This documentation page still links to the [tyk_quickstart](https://github.com/TykTechnologies/tyk_quickstart) repo, which no longer exists.

**Comment by marksou** [comment]
Hi @l3ender This page was removed from the documentation a while ago, so I'm assuming you got there via a Google search?

**Comment by l3ender** [comment]
It was originally sent to me from a Tyk rep after we demoed the product ~1-2 months back, and then I found it again via Google today.

This repo (pro docker demo) is very helpful and it'd be great to see it in higher visibility in the docs. For anyone wanting to spin up a quick instance, it's a lot more feasible as opposed to the other docs describing setting up the separate components.

Thanks!
