### ISSUE TITLE
Document and fill out config files

### ISSUE THREAD

**Issue by gwshaw** [TykTechnologies/tyk-pro-docker-demo#4]
As a new user, I want to be able to easily find and configure the features of Tyk.

In evaluating Tyk I found that it requires FAR too much Googling to determine how to use its many features. External documentation will always be out of date and incomplete. The best course is documentation right inside the configuration files.

The configuration files should contain ALL config options regardless of their default values and the desired current value. That is, if an option should currently be set to false and the default value is false, and entry MUST still exist in the config file as false. Human-readable config files are for Humans, not computers. They should be verbose and explanatory. Since they are typically loaded once at startup the size and complexity are not relevant.

As an example, see the config files for the Sublime text editor. For example:
(Sublime Text/Preferences/Settings)
```
/ Place your settings in the file "Packages/User/Preferences.sublime-settings",
// which overrides the settings in here.
//
// Settings may also be placed in syntax-specific setting files, for
// example, in Packages/User/Python.sublime-settings for python files.
{
    // Sets the colors used within the text area
    "color_scheme": "Packages/Color Scheme - Default/Monokai.tmTheme",

    // Note that the font_face and font_size are overridden in the platform
    // specific settings file, for example, "Preferences (Linux).sublime-settings".
    // Because of this, setting them here will have no effect: you must set them
    // in your User File Preferences.
    "font_face": "",
    "font_size": 10,

    // Valid options are "no_bold", "no_italic", "no_antialias", "gray_antialias",
    // "subpixel_antialias", "no_round" (OS X only), "gdi" (Windows only) and
    // "directwrite" (Windows only)
    "font_options": [],

    // Characters that are considered to separate words
    "word_separators": "./\\()\"'-:,.;<>~!@#$%^&*|+=[]{}`~?",

    // Set to false to prevent line numbers being drawn in the gutter
    "line_numbers": true,

    // Set to false to hide the gutter altogether
    "gutter": true,

    // Spacing between the gutter and the text
    "margin": 4,
   ...
}
```

**Comment by zalbiraw** [comment]
Documentation has been improved and is located on the tyk.io/docs
