### ISSUE TITLE
Supply configured versions of must available features

### ISSUE THREAD

**Issue by gwshaw** [TykTechnologies/tyk-pro-docker-demo#5]
As a new user, I want to be able to easily find and configure the features of Tyk.

In addition to documented config files (previous issue), having most features implemented in the demo and called out greatly simplifies learning about the system and making the parts work. If is better to have the user evaluating the system need to turn off features than struggle to determine how to implement them (where are all the places that need to be touched?) The volume definitions in docker-compose inherently call out files and itself may be adequate to point to the interesting parts for the user to browse (Along with appropriate README.md files).

A "simple" demo is useless for evaluating a system that will be used for millions to billions of API calls a month.

Additional suggestions are better comments, using standard nomenclature (listen-path --> basepath), and following standards (accepting standard HTTP cache headers for caching) greatly reduce the learning curve. All of these greatly reduce the learning curve.

**Comment by zalbiraw** [comment]
Documentation has been improved and is located on the tyk.io/docs
