### ISSUE TITLE
Shell script does not run with python 3

### ISSUE THREAD

**Issue by thomas-siegrist** [TykTechnologies/tyk-pro-docker-demo#6]
The shell script doesn't work with python 3. Print needs to be used as a function with parameter.

Original Code:
```
ORG_ID=$(echo $ORG_DATA | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["Meta"]')
```
Working example with python 3:
```
ORG_ID=$(echo $ORG_DATA | python -c 'import json,sys;obj=json.load(sys.stdin);print(obj["Meta"])')
```

**Comment by mvdan** [comment]
Is using Python 2 a problem? Our scripts use that version in multiple repositories, so switching to version 3 is not trivial.

If you're referring to the fact that we call `python` (which is often version 3, not 2) instead of `python2`, that's a different issue.
