### ISSUE TITLE
dashboard credentials 

### ISSUE THREAD

**Issue by abdullah-abunada** [TykTechnologies/tyk-pro-docker-demo#9]
Hi all,

After running docker-compose start tyk is running successfully, but I don't have  dashboard credentials.
please update the documentation of it.

note: I red another way of running docker container using setup.sh but its not working with me.
setup.sh service not found (I'm using mac os).

best

**Comment by matiasinsaurralde** [comment]
Hi, how are you calling `setup.sh`?

**Comment by abdullah-abunada** [comment]
sorry, I call it with reinforce in docker up command, now I rum it alone its works perfectly 
Thanks
